export const ActionTypes = {
    SET_EMPLOYES : "SET_EMPLOYES",
    SELECTED_EMPLOYE : "SELECTED_EMPLOYE",
    REMOVE_SELECTED_EMPLOYE : "REMOVE_SELECTED_EMPLOYE",
    SET_PROFILE_UTILISATEUR : "SET_PROFILE_UTILISATEUR",
    REMOVE_SELECTED_UTILISATEUR : "REMOVE_SELECTED_UTILISATEUR",
    SET_USER_LOGIN : "SET_USER_LOGIN",
    SET_CONVERSATION : "SET_CONVERSATION",
    SET_MESSAGE : "SET_MESSAGE"
}